### PR TITLE
Feature/deployment

### PR DESCRIPTION
**Pull request by hixi**
deployment config

### CODE REVIEW

**Comment by hixi** [comment]
This isn't the best way to go (duplicated dockerfiles), but it is for now the fastest way to get a deployment up and running. Feel free to reject and propose another solution.

**Comment by Excape** [comment]
@hixi Thank you so much! Everything seems to work on our end.

- Can we consolidate our Docker files? Seeing as the only difference for the Dockerfiles is in the one for `plaza_preprocessing`. Or alternatively copy your files into e.g. `docker/deploy`?

- We need to restart Graphhopper every time after the preprocessing has been done. Just swapping the file doesn't cause Graphhopper to update its graph data. Also, graphhopper creates a directory `*-gh`, which needs to be deleted between restarts to ensure that the updated file is used. To summarize, every time after `plaza_preprocessing` has run (finished), we need to 1) delete `/pbf/switzerland-processed.osm-gh` and 2) restart the Graphhopper container

**Comment by hixi** [comment]
Yes, we can. Keep in mind that the Dockerfile only has access to the context inside its folder and subfolders during build, so moving to `deploy` isn't an option unfortunately. I'll update the pull-request and remove the 'old' Dockerfiles, would it be possible for you to then update the circle-ci file if needed?

I'll think of a solution to restart the container after an update, maybe this isn't too hard after all...

**Comment by Excape** [comment]
@hixi Thanks! I will pull apart the docker files a little, again. Is it okay to have the docker-compose files in `deploy/`? They'll just point to the Dockerfiles in the root directory with the build context `..`

There is a small problem in `graphhopper-watcher` with [this line](https://github.com/geometalab/plazaroute/blob/83258aab8a7bbeba2b5025479e635dfe996fb68d/plaza_routing/docker/graphhopper/graphhopper-watcher.sh#L20)

When the graphhopper process firsts start up, it will fail to load the OSM file (since there is none yet) and exit. The `kill` command will later fail because that process already exited. Can we include a guard to only kill the process if it's still running?

**Comment by hixi** [comment]
The docker-compose files can live wherever it pleases you. Can you make the necessary changes to the messed up watcher or do you need help with that?

**Comment by Excape** [comment]
I managed to fix it myself. Not a pretty solution, but it works

I will merge the changes into master. Let me know if everything still works for the deployment!

**Pull request merged**
